Traceback (most recent call last):
  File "/home/runner/workspace/manage.py", line 22, in <module>
    main()
  File "/home/runner/workspace/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/nix/store/6dhxaza18jl6d29yczsqp0nf7lr07avj-python3.11-django-4.2.12/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/nix/store/6dhxaza18jl6d29yczsqp0nf7lr07avj-python3.11-django-4.2.12/lib/python3.11/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/nix/store/6dhxaza18jl6d29yczsqp0nf7lr07avj-python3.11-django-4.2.12/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/nix/store/6dhxaza18jl6d29yczsqp0nf7lr07avj-python3.11-django-4.2.12/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/6dhxaza18jl6d29yczsqp0nf7lr07avj-python3.11-django-4.2.12/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/workspace/myproject/settings.py", line 76, in <module>
    JWT_EXPIRATION_DELTA = datetime.timedelta(days=1)
                           ^^^^^^^^
NameError: name 'datetime' is not defined
